common/models/OrderProduct.php
<?php

namespace common\models;

use Yii;
use common\models\Product;

/**
 * This is the model class for table "order_product".
 *
 * @property int $product_id
 * @property int $order_id
 * @property int $count
 * @property string $price
 */
class OrderProduct extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order_product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'order_id'], 'required'],
            [['product_id', 'order_id', 'count'], 'integer'],
            [['price'], 'number'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'product_id' => 'Product ID',
            'order_id' => 'Order ID',
            'count' => 'Count',
            'price' => 'Price',
        ];
    }

    public function getProduct(){
        return $this->hasMany(Product::className(), ['id' => 'product_id']);
    }

}

frontend/controllers/CartController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\OrderProduct;
use common\models\Order;

/**
 * Site controller
 */
class CartController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $order = Yii::$app->cart->getOrder();
        if(empty($order->orderProducts)){
            return $this->goHome();
        }
        return $this->render('index', ['orderProducts' => $order->orderProducts]);
    }

    public function actionDelete($id)
    {
        Yii::$app->cart->delete($id, 1);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionPlus($id)
    {
        Yii::$app->cart->add($id, 1);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionOrder()
    {
        $model = Yii::$app->cart->getOrder();
        $model->scenario = Order::SCENARIO_ORDER;
        
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            $model->status = 1;
            $model->save();

            //work time
            if(date('G') >= 9 && date('G') <= 18){
                $this->sendEmail(Yii::$app->params['workTimeEmail'], $model->id);
            } else {
                $this->sendEmail(Yii::$app->params['notWorkTimeEmail'], $model->id);
            }

            return $this->redirect(['site/order-success']);

        }
        
        return $this->render('order', ['model' => $model]);
    }

    public function actionAdd()
    {
        $postData = Yii::$app->request->post();
        return json_encode([
            'success' => Yii::$app->cart->add($postData['product_id'], 1),
            'cartStatus' => Yii::$app->cart->status
        ]);
    }

    public function sendEmail($email, $orderId){
        Yii::$app->mailer->compose()
        ->setFrom([Yii::$app->params['adminEmail'] => Yii::$app->name . ' robot'])
        ->setTo($email)
        ->setSubject("Заказ №$orderId")
        ->setHtmlBody("Заказ №$orderId принят")
        ->send();
    }

}

frontend/views/cart/index.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Button;
?>
<div class="site-index">
    <table border="1">
        <tr>
            <td></td>
            <td>Название</td>
            <td>Цена</td>
            <td>Кол-во</td>
            <td></td>
        </tr>

        <?php foreach ($orderProducts as $orderProduct):?>
            <tr>
                <td>
                    <?= Html::img('/uploads/store/'.$orderProduct->product[0]->getImage()->filePath, ['width' => 100])?>
                </td>
                <td><?= $orderProduct->product[0]->title?></td>
                <td><?= $orderProduct->price?></td>
                <td><?= $orderProduct->count?></td>
                <td>
                    <?= Html::a('+', ['cart/plus', 'id' => $orderProduct->product[0]->id], [
                        'class'=>'btn btn-success',
                        'title' => 'Добавть'
                        ]
                    ) ?>
                    <?= Html::a('x', ['cart/delete', 'id' => $orderProduct->product[0]->id], [
                        'class'=>'btn btn-danger',
                        'title' => 'Удалить'
                        ]
                    ) ?>
                </td>
            </tr>
        <?php endforeach;?>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><?=  Yii::$app->cart->getAmount();?></td>
            </tr>
    </table>
    <?= Html::a('Оформить', ['cart/order'], [
        'class'=>'btn btn-primary',
        'title' => 'Оформить'
        ]
    ) ?>
</div>

frontend/views/cart/order.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model common\models\Product */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype'=>'multipart/form-data']]);?>

    <?= $form->field($model, 'first_name')->textInput() ?>

    <?= $form->field($model, 'last_name')->textInput() ?>

    <?= $form->field($model, 'email')->textInput() ?>

    <?= $form->field($model, 'phone')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Отправить заказ', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>